syntax "makefile" "[Mm]akefile$" "\.mk$"

KEYWORD:  "\<(ifeq|ifdef|ifneq|ifndef|else|endif)\>"
SECTION:  "^[^   ]+:"
OPERATOR: "[=,%]" "\+=|\?=|:=|&&|\|\|"
FUNCTION: "\$\((addprefix|patsubst|shell|sort|wildcard)\s"
PLAIN:    "[()$]"
STRING:   "\"(\\.|[^\\\"])*\"|'(\\.|[^\\'])*'"
VARIABLE: "\$+[{(][a-zA-Z0-9_-]+[})]"
VARIABLE: "\$[@^<*?%|+]"
VARIABLE: "\$\([@^<*?%+-][DF]\)"
ESCAPE:   "\$\$"
ESCAPE:   "\\.?"
COMMENT:  "(\s|^|@)#.*$"

# Show trailing whitespace
color ,green "[[:space:]]+$"
